### ISSUE TITLE
CLI query ignores id `0`

### ISSUE THREAD

**Issue by Senna46** [sunriselayer/sunrise#81]
Not displayed on CLI when position id and pool id are 0
```
ubuntu@ip-172-31-44-59:~$ sunrised q liquiditypool show-position 0
position:
  position:
    address: sunrise18w30e2qvexwmge4mct99n7mmreczv8sacr322z
    liquidity: "1207214655476724156074205035988"
    lower_tick: "16621"
    upper_tick: "21103"
  token_base:
    amount: "49616047755"
    denom: ibc/uatom
  token_quote:
    amount: "330000000000"
    denom: urise

ubuntu@ip-172-31-44-59:~$ sunrised q liquiditypool show-position 1
position:
  position:
    address: sunrise18w30e2qvexwmge4mct99n7mmreczv8sacr322z
    id: "1"
    liquidity: "199934807335959038964097809233"
    lower_tick: "-4155"
    pool_id: "1"
    upper_tick: "4054"
  token_base:
    amount: "36699818939"
    denom: urise
  token_quote:
    amount: "37486014990"
    denom: ibc/uusdc


```
